name: Documentation

on:
  workflow_dispatch:

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: docfx/docfx.json

    - name: Publish
      run: |
        git config user.email git@github.com
        git config user.name 'GitHub Actions'
        git add ./docs -f
        git commit -m 'publish site'
        git push -f -u origin master:gh-pages
